// mobile_ui.js — the phone shell (below 768px) from the Finchat Mobile design.
//
// Not included by hand: middleware/pwaHead.js adds this script and
// mobile_ui.css to every page as it is served, the same way it adds the PWA
// tags, so a page regenerated by the design tool keeps its phone layout.
//
// What it owns, on phones only (tablets and desktop are untouched):
//   - the app bar: menu, page title + subtitle, page actions, bell + badge.
//     Each page's own top header is hidden by mobile_ui.css instead;
//   - the drawer's phone look (Lucide icons, Recent inside the one scroll);
//   - bottom sheets, a confirm/prompt dialog and the toast, as window.fcMobile,
//     so pages build phone UI from the same parts instead of copying markup;
//   - the notifications sheet behind the bell.
//
// Pages talk to it through window.fcMobile: setTitle, setBack, setActions,
// sheet, actions, confirm, prompt, toast, icon, openNotifications.
(function () {
  'use strict';
  if (window.fcMobile) return;

  var PHONE = '(max-width: 767px)';
  var mq = window.matchMedia ? window.matchMedia(PHONE) : { matches: false };
  var isPhone = function () { return !!mq.matches; };

  // ── Pages ────────────────────────────────────────────────────────────────
  // bar: false — the page draws its own phone header (Chat, Neural Space, the
  // canvas editors). Pages missing from this list get no phone shell at all:
  // login, signup and the public share pages keep their own designs.
  var PAGES = [
    ['finchat_chat', { bar: false }],
    ['finchat_inbox', { bar: false }],
    ['finchat_dashboard', { title: 'Operations', sub: 'Agent Operations Dashboard' }],
    ['finchat_agents', { title: 'Agents' }],
    ['finchat_groupchat', { title: 'Group Chat', sub: 'agents + you, one room' }],
    ['finchat_reports', { title: 'Memory reports' }],
    ['finchat_knowledge', { title: 'Knowledge' }],
    ['finchat_settings', { title: 'Settings' }],
    ['finchat_neuralmap', { title: 'Neural Map' }],
    // Model Lab's header is where the map is renamed, so it keeps its own.
    ['finchat_neuralnetwork', { bar: false }],
    ['finchat_agentmap', { title: 'Agent Map', sub: 'Ask Plato — watch the route form live' }],
    ['finchat_planning', { title: 'Planning' }],
    ['finchat_blockchain', { title: 'Blockchain anchoring', sub: 'Settings' }],
    ['finchat_audit', { title: 'Security & audit', sub: 'Settings' }],
    ['finchat_neuralspace', { bar: false }],
    ['finchat_mindmap', { bar: false }],
    ['finchat_boards', { bar: false }]
  ];
  function pageConfig() {
    var p = location.pathname.toLowerCase();
    for (var i = 0; i < PAGES.length; i++) if (p.indexOf(PAGES[i][0]) >= 0) return PAGES[i][1];
    return null;
  }

  var root = document.documentElement;
  var cfg = pageConfig();
  if (!cfg) { window.fcMobile = null; return; }
  root.classList.add('fcm-on');
  if (cfg.bar !== false) root.classList.add('fcm-bar-on');

  // ── Icons ────────────────────────────────────────────────────────────────
  // Lucide (lucide.dev) at stroke 2.75, as the design system asks. "c:" is a
  // circle (cx,cy,r), "r:" a rect (x,y,w,h,rx); anything else is a path.
  var P = {
    menu: ['M4 6h16', 'M4 12h16', 'M4 18h16'],
    bell: ['M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9', 'M10.3 21a1.94 1.94 0 0 0 3.4 0'],
    more: ['c:12,12,1', 'c:19,12,1', 'c:5,12,1'],
    chevronDown: ['m6 9 6 6 6-6'], chevronLeft: ['m15 18-6-6 6-6'], chevronRight: ['m9 18 6-6-6-6'],
    clip: ['m21.44 11.05-9.19 9.19a6 6 0 0 1-8.49-8.49l8.57-8.57A4 4 0 1 1 18 8.84l-8.59 8.57a2 2 0 0 1-2.83-2.83l8.49-8.48'],
    link: ['M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71', 'M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71'],
    globe: ['c:12,12,10', 'M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20', 'M2 12h20'],
    cap: ['M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z', 'M22 10v6', 'M6 12.5V16a6 3 0 0 0 12 0v-3.5'],
    arrowUp: ['m5 12 7-7 7 7', 'M12 19V5'],
    mic: ['M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z', 'M19 10v2a7 7 0 0 1-14 0v-2', 'M12 19v3'],
    x: ['M18 6 6 18', 'm6 6 12 12'], check: ['M20 6 9 17l-5-5'], plus: ['M5 12h14', 'M12 5v14'], minus: ['M5 12h14'],
    copy: ['r:8,8,14,14,2', 'M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2'],
    trend: ['M22 7 13.5 15.5 8.5 10.5 2 17', 'M16 7h6v6'], target: ['c:12,12,10', 'c:12,12,6', 'c:12,12,2'],
    dash: ['r:3,3,7,9,1', 'r:14,3,7,5,1', 'r:14,12,7,9,1', 'r:3,16,7,5,1'],
    bot: ['M12 8V4H8', 'r:4,8,16,12,2', 'M2 14h2', 'M20 14h2', 'M15 13v2', 'M9 13v2'],
    chat: ['M7.9 20A9 9 0 1 0 4 16.1L2 22Z'],
    group: ['M14 9a2 2 0 0 1-2 2H6l-4 4V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2z', 'M18 9h2a2 2 0 0 1 2 2v11l-4-4h-6a2 2 0 0 1-2-2v-1'],
    sparkle: ['M12 3l1.9 5.8L20 10.7l-6.1 1.9L12 18.5l-1.9-5.9L4 10.7l6.1-1.9z'],
    scatter: ['c:7.5,7.5,3', 'c:18.5,5.5,2.5', 'c:11.5,18.5,2.5', 'c:19.5,15.5,1.5'],
    hub: ['c:12,12,2.5', 'c:5,5,2', 'c:19,5,2', 'c:5,19,2', 'c:19,19,2', 'M10.2 10.2 6.4 6.4', 'M13.8 10.2l3.8-3.8', 'M10.2 13.8l-3.8 3.8', 'M13.8 13.8l3.8 3.8'],
    map: ['c:11,11,8', 'm21 21-4.3-4.3', 'M11 7v4l3 2'],
    plan: ['r:3,3,8,8,2', 'r:13,13,8,8,2', 'M7 11v4a2 2 0 0 0 2 2h4'],
    report: ['r:3,3,18,18,2', 'M8 17v-3', 'M12 17V9', 'M16 17v-6'],
    book: ['M12 7v14', 'M3 18a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h5a4 4 0 0 1 4 4 4 4 0 0 1 4-4h5a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-6a3 3 0 0 0-3 3 3 3 0 0 0-3-3z'],
    settings: ['M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z', 'c:12,12,3'],
    search: ['c:11,11,8', 'm21 21-4.3-4.3'],
    shield: ['M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z', 'm9 12 2 2 4-4'],
    alert: ['m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3', 'M12 9v4', 'M12 17h.01'],
    rocket: ['M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z', 'm12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z', 'M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0', 'M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5'],
    sunrise: ['M12 2v8', 'm4.93 10.93 1.41 1.41', 'M2 18h2', 'M20 18h2', 'm19.07 10.93-1.41 1.41', 'M22 22H2', 'm8 6 4-4 4 4', 'M16 18a4 4 0 0 0-8 0'],
    trash: ['M3 6h18', 'M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6', 'M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2'],
    pencil: ['M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z'],
    split: ['M16 3h5v5', 'M8 3H3v5', 'M12 22v-8.3a4 4 0 0 0-1.17-2.87L3 3', 'm15 9 6-6'],
    tree: ['r:16,16,6,6,1', 'r:2,16,6,6,1', 'r:9,2,6,6,1', 'M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3', 'M12 12V8'],
    download: ['M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4', 'm7 10 5 5 5-5', 'M12 15V3'],
    refresh: ['M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8', 'M21 3v5h-5', 'M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16', 'M8 16H3v5'],
    file: ['M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z', 'M14 2v4a2 2 0 0 0 2 2h4'],
    camera: ['M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z', 'c:12,13,3'],
    image: ['r:3,3,18,18,2', 'c:9,9,2', 'm21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21'],
    brain: ['M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z', 'M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z', 'M12 5v13'],
    zap: ['M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z'],
    gavel: ['m14 13-8.381 8.38a1 1 0 0 1-3.001-3l8.384-8.381', 'm16 16 6-6', 'm21.5 10.5-8-8', 'm8 8 6-6', 'm8.5 7.5 8 8'],
    moon: ['M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z'],
    history: ['M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8', 'M3 3v5h5', 'M12 7v5l4 2'],
    flag: ['M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z', 'M4 22v-7'],
    send: ['M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z', 'm21.854 2.147-10.94 10.939'],
    trophy: ['M6 9H4.5a2.5 2.5 0 0 1 0-5H6', 'M18 9h1.5a2.5 2.5 0 0 0 0-5H18', 'M4 22h16', 'M18 2H6v7a6 6 0 0 0 12 0V2Z', 'M12 15v7'],
    bars: ['M3 3v18h18', 'M18 17V9', 'M13 17V5', 'M8 17v-3'],
    landmark: ['M3 22h18', 'M6 18v-7', 'M10 18v-7', 'M14 18v-7', 'M18 18v-7', 'm12 2 8 5H4z'],
    clipboard: ['r:8,2,8,4,1', 'M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2'],
    kanban: ['M6 5v11', 'M12 5v6', 'M18 5v14'],
    queue: ['M3 6h18', 'M3 12h12', 'M3 18h6'],
    tools: ['M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z'],
    flame: ['M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z'],
    share: ['c:18,5,3', 'c:6,12,3', 'c:18,19,3', 'M8.59 13.51l6.83 3.98', 'M15.41 6.51l-6.82 3.98'],
    logout: ['M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4', 'm16 17 5-5-5-5', 'M21 12H9'],
    user: ['c:12,8,5', 'M20 21a8 8 0 0 0-16 0'],
    help: ['c:12,12,10', 'M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3', 'M12 17h.01']
  };
  function icon(name, extraClass) {
    var parts = (P[name] || []).map(function (d) {
      if (d.indexOf('c:') === 0) { var c = d.slice(2).split(','); return '<circle cx="' + c[0] + '" cy="' + c[1] + '" r="' + c[2] + '"/>'; }
      if (d.indexOf('r:') === 0) { var r = d.slice(2).split(','); return '<rect x="' + r[0] + '" y="' + r[1] + '" width="' + r[2] + '" height="' + r[3] + '" rx="' + r[4] + '"/>'; }
      return '<path d="' + d + '"/>';
    }).join('');
    return '<svg class="fcm-ic' + (extraClass ? ' ' + extraClass : '') + '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + parts + '</svg>';
  }

  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }
  function token() {
    try {
      var sess = JSON.parse(sessionStorage.getItem('finchat_user') || localStorage.getItem('finchat_session') || 'null') || {};
      return localStorage.getItem('finchat_token') || sessionStorage.getItem('finchat_token') || sess.token || '';
    } catch (e) { return ''; }
  }
  var API = location.protocol.indexOf('http') === 0 ? '' : 'http://localhost:3000';

  // ── Toast ────────────────────────────────────────────────────────────────
  var toastEl = null, toastTimer = null;
  function toast(text) {
    if (!toastEl) {
      toastEl = document.createElement('div');
      toastEl.className = 'fcm-toast';
      toastEl.setAttribute('role', 'status');
      document.body.appendChild(toastEl);
    }
    toastEl.innerHTML = icon('check') + '<span>' + esc(text) + '</span>';
    // Lifted clear of a pinned composer (Chat, an open group thread).
    var composer = document.querySelector('.fcm-has-composer');
    toastEl.classList.toggle('fcm-toast-high', !!(composer && composer.offsetParent));
    // Next frame, so a toast created this tick still animates in.
    requestAnimationFrame(function () { toastEl.classList.add('fcm-show'); });
    clearTimeout(toastTimer);
    toastTimer = setTimeout(function () { toastEl.classList.remove('fcm-show'); }, 2400);
  }

  // ── Bottom sheet ─────────────────────────────────────────────────────────
  // One sheet at a time. opts: { title, action:{label,onClick}, className,
  // render(body) | items:[...] , onClose }. Items: { icon, img, label, sub,
  // on, danger, onClick } — an item with `img` renders as a person row (the
  // agent picker), one without as an action row.
  var sheetState = null;
  function ensureSheet() {
    var scrim = document.getElementById('fcmScrim');
    if (scrim) return;
    scrim = document.createElement('div');
    scrim.id = 'fcmScrim';
    scrim.className = 'fcm-scrim';
    scrim.addEventListener('click', function () { closeSheet(); });
    var sheet = document.createElement('div');
    sheet.id = 'fcmSheet';
    sheet.className = 'fcm-sheet';
    sheet.setAttribute('role', 'dialog');
    sheet.setAttribute('aria-modal', 'true');
    sheet.innerHTML = '<div class="fcm-sheet-grip"><span></span></div><div class="fcm-sheet-head"></div><div class="fcm-sheet-body"></div>';
    document.body.appendChild(scrim);
    document.body.appendChild(sheet);
    // Drag the grip or the title down to dismiss, as on a native sheet.
    var startY = null, dy = 0;
    var grab = function (e) { startY = e.touches[0].clientY; dy = 0; sheet.style.transition = 'none'; };
    var move = function (e) {
      if (startY == null) return;
      dy = Math.max(0, e.touches[0].clientY - startY);
      sheet.style.transform = 'translateY(' + dy + 'px)';
    };
    var drop = function () {
      if (startY == null) return;
      startY = null;
      sheet.style.transition = '';
      sheet.style.transform = '';
      if (dy > 80) closeSheet();
    };
    [sheet.querySelector('.fcm-sheet-grip'), sheet.querySelector('.fcm-sheet-head')].forEach(function (h) {
      h.addEventListener('touchstart', grab, { passive: true });
      h.addEventListener('touchmove', move, { passive: true });
      h.addEventListener('touchend', drop);
      h.addEventListener('touchcancel', drop);
    });
  }
  function itemsHTML(items) {
    return items.map(function (it, i) {
      if (it.img || it.avatar) {
        var face = it.avatar || '<img src="' + esc(it.img) + '" alt="">';
        return '<button type="button" class="fcm-person' + (it.on ? ' fcm-on' : '') + '" data-i="' + i + '">' +
          '<span class="fcm-person-face">' + face + '</span>' +
          '<span class="fcm-person-text"><span class="fcm-person-name">' + esc(it.label) + '</span>' +
          (it.sub ? '<span class="fcm-person-sub">' + esc(it.sub) + '</span>' : '') + '</span>' +
          (it.on ? '<span class="fcm-person-check">' + icon('check') + '</span>' : '') + '</button>';
      }
      return '<button type="button" class="fcm-action' + (it.danger ? ' fcm-danger' : '') + '" data-i="' + i + '"' + (it.disabled ? ' disabled' : '') + '>' +
        (it.icon ? icon(it.icon) : '') + '<span>' + esc(it.label) + '</span>' +
        (it.sub ? '<span class="fcm-action-sub">' + esc(it.sub) + '</span>' : '') + '</button>';
    }).join('');
  }
  function sheet(opts) {
    ensureSheet();
    if (sheetState) finishClose(false);
    var el = document.getElementById('fcmSheet');
    var head = el.querySelector('.fcm-sheet-head');
    var body = el.querySelector('.fcm-sheet-body');
    el.className = 'fcm-sheet' + (opts.className ? ' ' + opts.className : '');
    head.innerHTML = '<h3>' + esc(opts.title || '') + '</h3>' +
      (opts.action ? '<button type="button" class="fcm-ghost" data-act>' + esc(opts.action.label) + '</button>' : '');
    head.style.display = opts.title || opts.action ? '' : 'none';
    if (opts.action) head.querySelector('[data-act]').onclick = function () { opts.action.onClick(api); };
    body.innerHTML = '';
    var api = { body: body, close: closeSheet, el: el };
    if (opts.items) {
      body.innerHTML = itemsHTML(opts.items);
      body.querySelectorAll('[data-i]').forEach(function (b) {
        b.onclick = function () {
          var it = opts.items[+b.getAttribute('data-i')];
          if (it.keepOpen) { it.onClick && it.onClick(api); return; }
          closeSheet();
          // After the sheet starts closing, so an action that opens another
          // sheet or a dialog is not torn down by this one.
          if (it.onClick) setTimeout(function () { it.onClick(api); }, 0);
        };
      });
    }
    if (opts.render) opts.render(body, api);
    sheetState = { opts: opts, api: api };
    root.classList.add('fcm-sheet-open');
    document.getElementById('fcmScrim').classList.add('fcm-show');
    requestAnimationFrame(function () { el.classList.add('fcm-show'); });
    return api;
  }
  function finishClose(animate) {
    var st = sheetState;
    sheetState = null;
    root.classList.remove('fcm-sheet-open');
    var el = document.getElementById('fcmSheet');
    var scrim = document.getElementById('fcmScrim');
    if (el) el.classList.remove('fcm-show');
    if (scrim) scrim.classList.remove('fcm-show');
    if (st && st.opts.onClose) try { st.opts.onClose(); } catch (e) {}
  }
  function closeSheet() { if (sheetState) finishClose(true); }

  // ── Dialog ───────────────────────────────────────────────────────────────
  // confirm({title, body, cta, danger, cancel:false}) and prompt({title, body,
  // value, placeholder, cta}) both resolve a Promise — false/null on cancel.
  function dialog(opts, withInput) {
    return new Promise(function (resolve) {
      closeSheet();
      var wrap = document.createElement('div');
      wrap.className = 'fcm-dialog-wrap';
      wrap.innerHTML =
        '<div class="fcm-dialog" role="alertdialog" aria-modal="true">' +
          '<div class="fcm-dialog-title">' + esc(opts.title || '') + '</div>' +
          (opts.body ? '<div class="fcm-dialog-body">' + esc(opts.body) + '</div>' : '') +
          (withInput ? '<input class="fcm-input" type="text">' : '') +
          '<div class="fcm-dialog-actions">' +
            '<button type="button" class="fcm-btn fcm-btn-primary' + (opts.danger ? ' fcm-btn-danger' : '') + '" data-ok>' + esc(opts.cta || 'OK') + '</button>' +
            (opts.cancel === false ? '' : '<button type="button" class="fcm-btn fcm-btn-secondary" data-cancel>Cancel</button>') +
          '</div>' +
        '</div>';
      document.body.appendChild(wrap);
      var input = wrap.querySelector('input');
      if (input) { input.value = opts.value || ''; input.placeholder = opts.placeholder || ''; }
      var done = function (val) {
        wrap.classList.remove('fcm-show');
        document.removeEventListener('keydown', onKey);
        setTimeout(function () { wrap.remove(); }, 220);
        resolve(val);
      };
      var onKey = function (e) {
        if (e.key === 'Escape') done(withInput ? null : false);
        if (e.key === 'Enter' && input) done(input.value);
      };
      document.addEventListener('keydown', onKey);
      wrap.querySelector('[data-ok]').onclick = function () { done(withInput ? input.value : true); };
      var c = wrap.querySelector('[data-cancel]');
      if (c) c.onclick = function () { done(withInput ? null : false); };
      wrap.addEventListener('click', function (e) { if (e.target === wrap) done(withInput ? null : false); });
      requestAnimationFrame(function () {
        wrap.classList.add('fcm-show');
        if (input) { input.focus(); input.select(); }
      });
    });
  }

  // ── App bar ──────────────────────────────────────────────────────────────
  // Seeded now, not when the bar is built: a page script can set its title or
  // actions before DOMContentLoaded, and building must not wipe that.
  var bar = null, barState = { title: cfg.title || '', sub: cfg.sub || '', back: null, actions: [] };
  function buildBar() {
    if (cfg.bar === false || bar) return;
    bar = document.createElement('header');
    bar.id = 'fcmBar';
    bar.className = 'fcm-bar';
    bar.innerHTML =
      '<button type="button" class="fcm-circ" data-fcm-nav aria-label="Menu">' + icon('menu') + '</button>' +
      '<div class="fcm-titles"><div class="fcm-title"></div><div class="fcm-sub"></div></div>' +
      '<div class="fcm-bar-actions"></div>' +
      bellHTML();
    document.body.insertBefore(bar, document.body.firstChild);
    bar.querySelector('[data-fcm-nav]').addEventListener('click', function () {
      if (barState.back) barState.back(); else openDrawer();
    });
    paintBadges();
    paintBar();
  }
  function bellHTML() {
    return '<button type="button" class="fcm-circ fcm-bell" data-fcm-bell aria-label="Notifications">' + icon('bell') +
      '<span class="fcm-badge" hidden></span></button>';
  }
  // An SPA view's scripts run before the router announces it (fc:navigated),
  // so a view that set its own bar has already done so by then: only a view
  // that left the bar alone gets reset to its page's defaults.
  var barTouched = false;
  function resetBar() {
    if (barTouched) { barTouched = false; return; }
    var c = pageConfig() || {};
    barState = { title: c.title || '', sub: c.sub || '', back: null, actions: [] };
    paintBar();
  }
  function paintBar() {
    if (!bar) return;
    bar.querySelector('.fcm-title').textContent = barState.title;
    var sub = bar.querySelector('.fcm-sub');
    sub.textContent = barState.sub || '';
    sub.hidden = !barState.sub;
    var nav = bar.querySelector('[data-fcm-nav]');
    nav.innerHTML = icon(barState.back ? 'chevronLeft' : 'menu');
    nav.setAttribute('aria-label', barState.back ? 'Back' : 'Menu');
    var acts = bar.querySelector('.fcm-bar-actions');
    acts.innerHTML = barState.actions.map(function (a, i) {
      return '<button type="button" class="fcm-circ' + (a.primary ? ' fcm-circ-dark' : '') + '" data-i="' + i + '" aria-label="' + esc(a.label) + '">' + icon(a.icon) + '</button>';
    }).join('');
    acts.querySelectorAll('[data-i]').forEach(function (b) {
      b.onclick = function () { barState.actions[+b.getAttribute('data-i')].onClick(); };
    });
  }

  function openDrawer() {
    if (window.fcSidebarNav && window.fcSidebarNav.openDrawer) window.fcSidebarNav.openDrawer();
  }

  // ── Drawer, phone look ───────────────────────────────────────────────────
  // sidebar_nav.js builds one rail for every width; on a phone it gets the
  // design's Lucide icons (beside its Material ones, so CSS can pick per
  // width) and Recent moves inside the nav's scroll, so the drawer scrolls as
  // one list instead of two stacked boxes.
  var NAV_ICONS = { operations: 'dash', agents: 'bot', chat: 'chat', groupchat: 'group', neuralspace: 'scatter',
    neuralmap: 'hub', brainmodel: 'map', mindmap: 'plan', reports: 'report', knowledge: 'book', settings: 'settings' };
  function decorateDrawer() {
    var nav = document.getElementById('sideNav');
    if (!nav || !nav.classList.contains('sbn')) return;
    nav.querySelectorAll('.sbn-item[data-sbn-key]').forEach(function (a) {
      if (a.querySelector('.fcm-ic')) return;
      var name = NAV_ICONS[a.getAttribute('data-sbn-key')];
      if (name) a.insertAdjacentHTML('afterbegin', icon(name, 'fcm-navic'));
    });
    nav.querySelectorAll('.sbn-item.sbn-soon').forEach(function (a) {
      if (a.querySelector('.fcm-ic')) return;
      var label = a.textContent;
      if (/Governance/.test(label)) a.insertAdjacentHTML('afterbegin', icon('landmark', 'fcm-navic'));
      else a.classList.add('fcm-hide-phone');
    });
    var newBtn = nav.querySelector('#sbnNewChat');
    if (newBtn && !newBtn.querySelector('.fcm-ic')) newBtn.insertAdjacentHTML('afterbegin', icon('plus', 'fcm-navic'));
    placeRecents(nav);
  }
  function placeRecents(nav) {
    var wrap = nav.querySelector('.sbn-recentwrap');
    var scroll = nav.querySelector('.sbn-scroll');
    if (!wrap || !scroll) return;
    if (isPhone()) { if (wrap.parentNode !== scroll) scroll.insertBefore(wrap, scroll.firstChild); }
    else if (wrap.parentNode === scroll) nav.insertBefore(wrap, scroll);
  }

  // Recent rows: on a phone "⋯" opens a sheet of the row's own actions. The
  // sheet clicks the row's existing (hidden) buttons, so copy / rename /
  // delete stay implemented in one place — sidebar_nav.js, or Chat's painter.
  var RECENT_ACTIONS = [['branch', 'split', 'Branch into a new chat'], ['mindmap', 'tree', 'Build a mind map'],
    ['rename', 'pencil', 'Rename'], ['copy', 'copy', 'Copy conversation'], ['export', 'download', 'Export JSON'], ['delete', 'trash', 'Delete conversation']];
  function recentSheet(row) {
    var title = row.getAttribute('data-title') || (row.textContent || '').trim();
    var items = [];
    RECENT_ACTIONS.forEach(function (a) {
      var btn = row.querySelector('[data-act="' + a[0] + '"]');
      if (!btn) return;
      items.push({ icon: a[1], label: a[2], danger: a[0] === 'delete', onClick: function () { btn.click(); } });
    });
    if (!items.length) return false;
    sheet({ title: title, className: 'fcm-sheet-actions', items: items });
    return true;
  }
  document.addEventListener('click', function (e) {
    if (!isPhone()) return;
    var more = e.target.closest && e.target.closest('#sideNav .sbn-rmore');
    if (!more) return;
    var row = more.closest('[data-sid]') || more.closest('.sbn-recent');
    if (!row) return;
    // Capture phase: runs before the row's own handler swaps in inline actions.
    if (recentSheet(row)) { e.preventDefault(); e.stopPropagation(); closeDrawerNow(); }
  }, true);
  function closeDrawerNow() {
    if (window.fcSidebarNav && window.fcSidebarNav.closeDrawer) window.fcSidebarNav.closeDrawer();
  }

  // ── Notifications ────────────────────────────────────────────────────────
  var NT = {
    approval: ['shield', 'fcm-nt-approval'], fraud: ['alert', 'fcm-nt-fraud'], briefing: ['sunrise', 'fcm-nt-briefing'],
    mission: ['rocket', 'fcm-nt-mission'], group_chat: ['group', 'fcm-nt-group'], debate: ['gavel', 'fcm-nt-approval'],
    system: ['bell', 'fcm-nt-mission']
  };
  var unread = 0, lastWidgetCount = 0;
  function paintBadges() {
    document.querySelectorAll('[data-fcm-bell] .fcm-badge').forEach(function (b) {
      b.textContent = unread > 99 ? '99+' : String(unread);
      b.hidden = !(unread > 0);
    });
  }
  // Any [data-fcm-bell] — the bar's, or a page's own bell that opts in (Chat)
  // — opens the sheet on a phone. Capture phase, so a page bell's own onclick
  // (its desktop dropdown) never runs there.
  document.addEventListener('click', function (e) {
    var bell = e.target.closest && e.target.closest('[data-fcm-bell]');
    if (!bell || !isPhone()) return;
    e.preventDefault();
    e.stopPropagation();
    openNotifications();
  }, true);
  function refreshCount() {
    var t = token();
    if (!t) return;
    fetch(API + '/api/notifications/unread-count', { headers: { Authorization: 'Bearer ' + t } })
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (d) { if (d && typeof d.count === 'number') { unread = d.count; paintBadges(); } })
      .catch(function () {});
  }
  // notifications_widget.js reports every badge refresh it makes; while it is
  // polling, this file doesn't poll the same endpoint a second time.
  window.addEventListener('fc:notif-count', function (e) {
    lastWidgetCount = Date.now();
    unread = e.detail || 0;
    paintBadges();
  });
  function timeAgo(ts) {
    var s = Math.floor((Date.now() - new Date(ts).getTime()) / 1000);
    if (s < 60) return 'now';
    if (s < 3600) return Math.floor(s / 60) + 'm';
    if (s < 86400) return Math.floor(s / 3600) + 'h';
    return Math.floor(s / 86400) + 'd';
  }
  function snippet(md) {
    if (window.fcNotifications && window.fcNotifications.snippet) return window.fcNotifications.snippet(md, 140);
    return esc(String(md || '').replace(/[#*_`>]/g, '').replace(/\s+/g, ' ').trim().slice(0, 140));
  }
  function ensureWidget() {
    if (window.fcNotifications || document.querySelector('script[src*="notifications_widget.js"]')) return;
    var s = document.createElement('script');
    s.src = 'notifications_widget.js';
    document.head.appendChild(s);
  }
  function openNotifications() {
    ensureWidget();
    var items = [];
    var api = sheet({
      title: 'Notifications',
      className: 'fcm-sheet-notifs',
      action: { label: 'Mark all read', onClick: function () { markAll(); } },
      render: function (body) { body.innerHTML = '<div class="fcm-empty">Loading…</div>'; }
    });
    function paint() {
      if (!items.length) { api.body.innerHTML = '<div class="fcm-empty">No notifications yet</div>'; return; }
      api.body.innerHTML = items.map(function (n, i) {
        var t = NT[n.type] || NT.system;
        return '<button type="button" class="fcm-notif' + (n.is_read ? '' : ' fcm-unread') + '" data-i="' + i + '">' +
          '<span class="fcm-notif-ic ' + t[1] + '">' + icon(t[0]) + '</span>' +
          '<span class="fcm-notif-text">' +
            '<span class="fcm-notif-top"><span class="fcm-notif-title">' + esc(n.title || 'Notification') + '</span>' +
            '<span class="fcm-notif-time">' + timeAgo(n.created_at) + '</span></span>' +
            '<span class="fcm-notif-body">' + snippet(n.content) + '</span>' +
          '</span>' +
          (n.is_read ? '' : '<span class="fcm-notif-dot"></span>') +
        '</button>';
      }).join('');
      api.body.querySelectorAll('[data-i]').forEach(function (b) {
        b.onclick = function () {
          var n = items[+b.getAttribute('data-i')];
          closeSheet();
          if (!n.is_read) { unread = Math.max(0, unread - 1); paintBadges(); }
          if (window.fcNotifications && window.fcNotifications.activate) window.fcNotifications.activate(n);
          else {
            fetch(API + '/api/notifications/' + n.notification_id + '/read', { method: 'POST', headers: { Authorization: 'Bearer ' + token() } }).catch(function () {});
            if (n.link) location.href = n.link;
          }
        };
      });
    }
    function markAll() {
      items.forEach(function (n) { n.is_read = true; });
      unread = 0; paintBadges(); paint();
      fetch(API + '/api/notifications/read-all', { method: 'POST', headers: { Authorization: 'Bearer ' + token() } }).catch(function () {});
      toast('All caught up');
    }
    fetch(API + '/api/notifications?limit=20', { headers: { Authorization: 'Bearer ' + token() } })
      .then(function (r) { return r.ok ? r.json() : { notifications: [] }; })
      .then(function (d) { items = d.notifications || []; if (sheetState && sheetState.api === api) paint(); })
      .catch(function () { if (sheetState && sheetState.api === api) api.body.innerHTML = '<div class="fcm-empty">Could not load notifications</div>'; });
  }

  // Static page markup asks for an icon with <span data-fcm-icon="name">.
  function hydrateIcons(scope) {
    (scope || document).querySelectorAll('[data-fcm-icon]').forEach(function (el) {
      if (el.firstChild) return;
      el.outerHTML = icon(el.getAttribute('data-fcm-icon'));
    });
  }

  // ── Wiring ───────────────────────────────────────────────────────────────
  function boot() {
    buildBar();
    decorateDrawer();
    hydrateIcons();
    var nav = document.getElementById('sideNav');
    if (nav && window.MutationObserver) {
      // sidebar_nav.js rebuilds the rail on a theme switch and repaints Recent.
      new MutationObserver(function () { decorateDrawer(); }).observe(nav, { childList: true });
    }
    refreshCount();
    setInterval(function () {
      if (document.hidden || !isPhone()) return;
      if (Date.now() - lastWidgetCount < 45000) return;
      refreshCount();
    }, 60000);
  }
  var onChange = function () {
    var nav = document.getElementById('sideNav');
    if (nav) placeRecents(nav);
    if (!isPhone()) closeSheet();
    if (window.fcSidebarNav && window.fcSidebarNav.syncActive) window.fcSidebarNav.syncActive();
  };
  if (mq.addEventListener) mq.addEventListener('change', onChange);
  else if (mq.addListener) mq.addListener(onChange);
  // SPA views (Knowledge, Reports, Settings, Planning) swap only <main>: the
  // bar stays, but its title and actions belong to the view.
  window.addEventListener('fc:navigating', function () { closeSheet(); barTouched = false; });
  window.addEventListener('fc:navigated', function () {
    resetBar();
    hydrateIcons();
  });
  document.addEventListener('keydown', function (e) { if (e.key === 'Escape') closeSheet(); });

  window.fcMobile = {
    isPhone: isPhone,
    icon: icon,
    hydrateIcons: hydrateIcons,
    esc: esc,
    toast: toast,
    sheet: sheet,
    closeSheet: closeSheet,
    // A list of actions in a sheet: actions('Title', [{icon,label,danger,onClick}]).
    actions: function (title, items) { return sheet({ title: title, className: 'fcm-sheet-actions', items: items }); },
    confirm: function (o) { return dialog(o || {}, false); },
    prompt: function (o) { return dialog(o || {}, true); },
    setTitle: function (title, sub) { barTouched = true; barState.title = title || ''; barState.sub = sub || ''; paintBar(); },
    setBack: function (fn) { barTouched = true; barState.back = typeof fn === 'function' ? fn : null; paintBar(); },
    setActions: function (list) { barTouched = true; barState.actions = list || []; paintBar(); },
    openNotifications: openNotifications,
    openDrawer: openDrawer,
    refreshCount: refreshCount
  };

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
  else boot();
})();
