// pwa.js — makes every page part of the installable app.
//
// Not included by hand: middleware/pwaHead.js adds this script (with the
// manifest link and home-screen meta tags) to every HTML page as it is served,
// so pages regenerated by the design tool stay installable.
(function () {
  // Registering on every page (not only from Settings, where push is switched
  // on) is what gives an installed app its offline screen. Same URL as
  // Settings uses, so it is one registration, not two.
  if ('serviceWorker' in navigator && location.protocol.indexOf('http') === 0) {
    window.addEventListener('load', function () {
      navigator.serviceWorker.register('/sw.js').catch(function () {});
    });
  }

  // The status bar of the installed app takes theme-color. The static value is
  // the light page background; a page in dark theme repaints it to match.
  function syncThemeColor() {
    var meta = document.querySelector('meta[name="theme-color"]');
    if (!meta || !document.body) return;
    var c = getComputedStyle(document.body).backgroundColor;
    if (c && c !== 'transparent' && c !== 'rgba(0, 0, 0, 0)') meta.setAttribute('content', c);
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', syncThemeColor);
  else syncThemeColor();
  // The theme toggle flips data-theme on <html>.
  if (window.MutationObserver) {
    new MutationObserver(syncThemeColor).observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] });
  }
})();
