// middleware/pwaHead.js — makes every HTML page part of the installable app.
//
// Adds the manifest link, home-screen meta tags and pwa.js (which registers the
// service worker) to each page's <head> as it is served. Done here rather than
// in the 20 HTML files because those files get regenerated by the design tool,
// and a page that lost these tags would quietly stop being installable.
//
// Pages still carry `<link rel="apple-touch-icon" href="/assets/favicon.svg">`.
// iOS ignores SVG home-screen icons, and two apple-touch-icon links leave it
// free to pick the wrong one, so that line is swapped for the PNG.
//
// Responses keep the static server's contract: Cache-Control no-cache, with an
// ETag so a revalidation is a cheap 304. A page's rewritten HTML is cached in
// memory until its file's mtime changes.
const fs = require('fs');
const path = require('path');

const PWA_HEAD = [
  '<link rel="manifest" href="/manifest.webmanifest">',
  '<meta name="theme-color" content="#f7f4ed">',
  '<link rel="apple-touch-icon" href="/assets/icons/apple-touch-icon.png">',
  '<meta name="mobile-web-app-capable" content="yes">',
  '<meta name="apple-mobile-web-app-capable" content="yes">',
  '<meta name="apple-mobile-web-app-title" content="FinChat">',
  '<meta name="apple-mobile-web-app-status-bar-style" content="default">',
  '<script src="/pwa.js" defer></script>'
].join('\n');

const SVG_TOUCH_ICON = /[ \t]*<link rel="apple-touch-icon" href="\/assets\/favicon\.svg">\r?\n?/g;

/** The page with the PWA tags added. Unchanged if it has no </head> or already links a manifest. */
function injectPwaHead(html) {
  if (/rel=["']manifest["']/i.test(html)) return html;
  const at = html.search(/<\/head>/i);
  if (at < 0) return html;
  const withTags = html.slice(0, at) + PWA_HEAD + '\n' + html.slice(at);
  return withTags.replace(SVG_TOUCH_ICON, '');
}

function pwaHead(frontendDir) {
  const root = path.resolve(frontendDir);
  const cache = new Map(); // absolute file → { mtimeMs, html }

  return async function pwaHeadMiddleware(req, res, next) {
    if (req.method !== 'GET' && req.method !== 'HEAD') return next();
    if (!/\.html$/i.test(req.path)) return next();

    let rel;
    try { rel = decodeURIComponent(req.path); } catch (e) { return next(); }
    const file = path.resolve(root, '.' + rel);
    if (!file.startsWith(root + path.sep)) return next(); // outside the frontend dir

    try {
      const st = await fs.promises.stat(file);
      if (!st.isFile()) return next();
      let hit = cache.get(file);
      if (!hit || hit.mtimeMs !== st.mtimeMs) {
        const raw = await fs.promises.readFile(file, 'utf8');
        hit = { mtimeMs: st.mtimeMs, html: injectPwaHead(raw) };
        cache.set(file, hit);
      }
      res.setHeader('Cache-Control', 'no-cache');
      res.type('html').send(hit.html); // res.send sets the ETag and answers 304 when fresh
    } catch (e) {
      next(); // missing or unreadable — let express.static decide
    }
  };
}

module.exports = { pwaHead, injectPwaHead, PWA_HEAD };
